# Generated by Django 5.2.5 on 2025-08-11 21:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cuerpo',
            field=wagtail.fields.StreamField([('hero', 4), ('tarjetas', 10), ('eventos', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título principal', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Texto debajo del título', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto del botón', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enlace del botón', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('boton_texto', 2), ('boton_url', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('titulo', 5), ('descripcion', 6), ('image', 7), ('link', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.DateBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('titulo', 5), ('descripcion', 6), ('fecha', 11), ('image', 7), ('link', 8)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {})}),
        ),
    ]
