# Generated by Django 5.2.5 on 2025-08-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_body_remove_homepage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='cuerpo',
            new_name='body',
        ),
    ]
