# Generated by Django 5.2.5 on 2025-08-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_menu_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='link_page',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
