# Generated by Django 5.2.4 on 2025-08-16 23:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_featuredimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('slider', 11), ('tarjetas', 16), ('eventos', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título principal', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Texto debajo del título', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto del botón', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enlace del botón', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('boton_texto', 2), ('boton_url', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.TextBlock', (), {'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('imagen', 5), ('titulo', 6), ('subtitulo', 7), ('boton_texto', 6), ('boton_url', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('slides', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {}), 13: ('wagtail.blocks.TextBlock', (), {}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 15: ('wagtail.blocks.StructBlock', [[('titulo', 12), ('descripcion', 13), ('image', 14), ('link', 8)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.DateBlock', (), {}), 18: ('wagtail.blocks.StructBlock', [[('titulo', 12), ('descripcion', 13), ('fecha', 17), ('image', 14), ('link', 8)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {})}),
        ),
    ]
