# Generated by Django 5.2.5 on 2025-08-19 21:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('slider', 11), ('card', 19), ('eventos', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título principal', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Texto debajo del título', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto del botón', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enlace del botón', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('boton_texto', 2), ('boton_url', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.TextBlock', (), {'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('imagen', 5), ('titulo', 6), ('subtitulo', 7), ('boton_texto', 6), ('boton_url', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('slides', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {}), 13: ('wagtail.blocks.TextBlock', (), {}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Ver más'}), 16: ('wagtail.blocks.CharBlock', (), {'default': '#ffffff'}), 17: ('wagtail.blocks.CharBlock', (), {'default': '#1D9DE2'}), 18: ('wagtail.blocks.StructBlock', [[('title', 12), ('text', 13), ('image', 14), ('link', 8), ('button_text', 15), ('background_color', 16), ('button_color', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.DateBlock', (), {}), 21: ('wagtail.blocks.StructBlock', [[('titulo', 12), ('descripcion', 13), ('fecha', 20), ('image', 14), ('link', 8)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {})}),
        ),
    ]
