# Generated by Django 5.2.4 on 2025-08-13 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_parent_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, help_text='Si este ítem es un submenú, selecciona su ítem padre.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem'),
        ),
    ]
